name: Build (and deploy on new tags)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: build and install cc65 components
        run: |
          git clone https://github.com/cc65/cc65 /tmp/cc65
          sudo make -C /tmp/cc65 ca65 ld65 avail
          ca65 --version
          
      - name: build and install cadius
        run: |
          git clone https://github.com/mach-kernel/cadius /tmp/cadius
          make -C /tmp/cadius
          sudo make -C /tmp/cadius install

      - name: build a2d
        env:
          TERM: xterm-256color
        run: |
          bin/setlang en && make && make package
          bin/setlang fr && make && make package
          bin/setlang it && make && make package
          bin/setlang es && make && make package
          bin/setlang de && make && make package

      - name: deploy new version
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.8.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}      
          artifacts: "out/*.2mg,out/*.po,res/README.txt"
          prerelease: true
